# Generated by Django 4.2.7 on 2023-11-23 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.BinaryField()),
                ('private_key', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, editable=False, max_digits=20)),
                ('timestamp', models.DateTimeField(editable=False)),
                ('signature', models.BinaryField()),
                ('recipient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='recipient_account', to='app.account')),
                ('sender', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='sender_account', to='app.account')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('index', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_hash', models.CharField(editable=False, max_length=5000)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='key_pair',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='keys', to='app.keypair'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
