# Generated by Django 4.2.7 on 2023-11-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='hash',
            field=models.CharField(default=0, editable=False, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='noune',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
