# Generated by Django 4.2.7 on 2023-11-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_block_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='previous_hash',
            field=models.BinaryField(max_length=5000),
        ),
    ]
