# Generated by Django 4.2.7 on 2023-11-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_block_previous_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='previous_hash',
            field=models.CharField(editable=False, max_length=5000),
        ),
    ]
