# Generated by Django 4.2.7 on 2023-11-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_block_previous_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(default=4, editable=False)),
                ('total', models.DecimalField(decimal_places=5, default=0, editable=False, max_digits=1000)),
            ],
        ),
    ]
